
<html>
<head>
<title>替换URL</title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<style>
.container {
  display: grid;
  grid-template-columns: 1fr;
  gap: 10px;
  align-items: start;
  justify-items: center;
  width: 200px;
  margin: 0 auto;
}
</style>
</head>
<body>
<div class="container">
  <input type="text" id="inputUrl" placeholder="轰炸内容" />
  <button onclick="replaceUrl()">确认</button>
  <button onclick="executeMultiple(5)">一键五连</button>
  <button onclick="executeMultiple(10)">一键十连</button>
</div>

<script>
function replaceUrl() {
  var inputValue = document.getElementById('inputUrl').value;
  var replacedUrl = 'https://api.day.app/H8bYFZN7BsAyGSkfa3cK44/张子怡/' + inputValue + '?icon=https://i.hd-r.cn/f57fb0be5327d0a2a7aa1fa86c8ae507.jpg';
  
  // 发送异步请求，替换URL并通知成功
  fetch(replacedUrl)
    .then(function(response) {
      if (response.ok) {
        showNotification("轰炸成功！");
      } else {
        showNotification("轰炸成功，但运行时出现错误！");
      }
    })
    .catch(function(error) {
      showNotification("轰炸成功，但运行时出现错误：" + error.message);
    });
}

function executeMultiple(count) {
  var delay = 200; // 间隔时间，单位为毫秒

  for (var i = 0; i < count; i++) {
    setTimeout(replaceUrl, i * delay);
  }
}

// 显示通知
function showNotification(message) {
  // 检查浏览器是否支持通知
  if (!("Notification" in window)) {
    console.log("该浏览器不支持桌面通知");
    return;
  }

  // 检查通知权限
  if (Notification.permission !== "granted") {
    Notification.requestPermission().then(function(permission) {
      if (permission === "granted") {
        createNotification(message);
      } else {
        console.log("用户未授予通知权限");
      }
    });
  } else {
    createNotification(message);
  }
}

// 创建通知
function createNotification(message) {
  var notification = new Notification("轰炸通知", {
    body: message,
    silent: true  // 设置通知为静默模式，不显示弹出窗口
  });

  // 5秒后自动关闭通知
  setTimeout(function() {
    notification.close();
  }, 1000);
}

// 添加事件监听器，捕获回车键按下事件
document.getElementById("inputUrl").addEventListener("keyup", function(event) {
  if (event.keyCode === 13) { // 回车键的键码为13
    event.preventDefault(); // 阻止默认的回车提交行为
    replaceUrl(); // 执行替换URL操作
  }
});
</script>
</body>
</html>
